### ISSUE TITLE
Start using closure-compiler artifact

### ISSUE THREAD

**Issue by lindner** [joestelmach/zipper#1]
cc is now available in maven central!  (by me...)

<dependency>
  <groupId>com.google.javascript</groupId>
  <artifactId>closure-compiler</artifactId>
  <version>r606</version>
</dependency>

I've hacked it together and it seems to work nicely (and a ton faster when you have a large number of files..)

**Comment by joestelmach** [comment]
That's great news! I should have some time this week to pull it in.

Are you using zipper?  I'm curious how you came across it...  

Thanks!

**Comment by lindner** [comment]
Thanks!

I'm trying to find a closure-specific replacement for the maven yuicompressor plugin that we use in Apache Shindig.  I found that closure wasn't in maven central, so I fixed that.

I found your plugin when searching for existing plugins (before going off and writing my own)

**Comment by joestelmach** [comment]
This is now committed to master.  Thanks again @lindner !

**Comment by lindner** [comment]
thanks!  I'll be experimenting with this in Shindig this week.

**Comment by joestelmach** [comment]
That's great - I hope it meets your needs.  If not, feel free to pass along any thoughts or criticism.
