### ISSUE TITLE
Support groups of assets

### ISSUE THREAD

**Issue by tauren** [joestelmach/zipper#2]
Zipper looks absolutely great, however I'm not sure if I can use it. I need to be able to specify which specific resource files to combine into an asset, and I need to create several JS and CSS files based on groups of resources. Zipper seems to be all-or-nothing.

My app has a core group of JS and CSS files that need to be included on the initial load. But then, as different features of the application are used, additional resources are pulled down on demand. I'd like to concat/optimize each group of resources into asset files, not everything into a single file. I don't want to load everything all up front for performance reasons.

Ideally there would be configuration options for defining multiple CSS and JS assets. Each asset would have a list of files to include, as well as define the order in which they should be included. 

Any thoughts on how much effort this would take to add to Zipper?

**Comment by joestelmach** [comment]
Hi Tauren,

Zipper actually already supports this.  The following configuration should produce two files, groupone.js and grouptwo.js, each containing the optimized concatenation of the file(s) given.

js.asset.groupone = foo.js
js.asset.groupone = bar.js

js.asset.grouptwo = baz.js

**Comment by tauren** [comment]
Sweet, I must have misread the documentation. Now that I look again, it makes sense. Thanks!
